const {
	REACT_APP_BSC_CHAIN_ID: BSC_CHAIN_ID = '',
	REACT_APP_BSC_CHAIN_ID_HEX: BSC_CHAIN_ID_HEX = '',
	REACT_APP_BSC_BLOCK_EXPLORER_URL: BSC_BLOCK_EXPLORER_URL = '',
	REACT_APP_BSC_RPC_URL: BSC_RPC_URL = '',
	REACT_APP_BSC_NAME: BSC_NAME = '',
} = process.env;

export {
	BSC_CHAIN_ID,
	BSC_CHAIN_ID_HEX,
	BSC_BLOCK_EXPLORER_URL,
	BSC_RPC_URL,
	BSC_NAME,
};
